travis:
  secure:
    BINSTAR_TOKEN: Sw/3ptVx/f2U+ojUpKPxhaxphbt06EFetsLJmJv9kzOeJEpDqu2uWe/HFEkauYep35JN1X+fpnpxxcEFeJgTV518yL9cjG88+x9tolT6ob98c5xOXuRs9mNo4b61vuReEICa3g3+1v2j0vMQ69LLf4fMK9ue5QoxeyvtHJaJSZGBYPSVezn3Z8gRxxUbXIeAnnYlNmjUYgm5j14dh+E5ltLT7qS9ASUl4v6cz33GMtZRW7Kp+bzrUmBHIjCVnBOF3+BJNQpEUXHqebZvj1MFAkYOGXAUFB5I+Re5rf5nuJDbdQCEePdEjoIaPLQSVG5SD9wA2q0lGMBlBc0WOTmXHRNyZYIid3+T2Bnspl8VU8uLfpNFWbL4oaWyfPtvERVarCVmtWPAHPzzkKIlAG+uVRWpUd6jNqYsA5YuYnbZST/slA78E+6nDRL3Tm8ZGBYI5y0OIHNZp2oWBN6aawCjwiufT1FdXBaur3z4w3SOv5zTBTTYwxpkRcF3a/+3k70QAQZv8bIIlTfzN2+FrAh2kdvx7g2MlrJ3pq+nLHv6ja9aYp9xAlXRjNL7SWS6YGXZiU9O6ax7eltDBOvyf8RmwxhzXklAh6t4OZO91j/zgrDRf3zYnwSeYkrj4DEhIFG+1XGplzhkRliT127gsXyoVnSSSsNulO15uKbpVtdgaRM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
